#!/usr/bin/env bash
# fixer.sh — post error analysis and assign Copilot coding agent to fix the PR

COMMIT_MARKER="[auto-pr-fixer]"
STATE_MARKER="<!-- auto-pr-fixer-state:"

fix_pr() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4" logs="$5"

  # Truncate logs for the comment
  local display_logs="$logs"
  if [[ "${#display_logs}" -gt 3000 ]]; then
    display_logs="${display_logs:0:3000}"$'\n... [truncated]'
  fi

  # Build the instruction for Copilot
  local fix_instruction
  fix_instruction=$(cat <<EOF
Fix the CI build failure for this PR. Here are the relevant error logs:

\`\`\`
$display_logs
\`\`\`

Please identify the root cause and provide a fix.
Only modify the minimum set of files needed to fix the build.
Do not modify lockfiles or go.sum unless the error is directly caused by them.
EOF
)

  # Post the error analysis comment
  local body
  body=$(cat <<EOF
## 🤖 Auto PR Fixer $COMMIT_MARKER

**CI build failure detected.** Assigning Copilot to fix it.

<details>
<summary>Error Logs (click to expand)</summary>

\`\`\`
$display_logs
\`\`\`
</details>

---
_Generated by [auto-pr-fixer](https://github.com/chrischangcode/auto-pr-fixer) for SHA \`$head_sha\`_
EOF
)

  gh api "repos/$owner/$repo/issues/$pr_num/comments" \
    -f body="$body" --silent

  echo "PR #$pr_num: posted error analysis comment."

  # Assign Copilot to the PR with a fix request
  assign_copilot "$owner" "$repo" "$pr_num" "$fix_instruction"
}

assign_copilot() {
  local owner="$1" repo="$2" pr_num="$3" instruction="$4"

  # Request a Copilot coding agent review with the fix instruction
  # Uses the POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers
  # endpoint to assign copilot as a reviewer
  echo "PR #$pr_num: requesting Copilot coding agent review..."

  gh api "repos/$owner/$repo/pulls/$pr_num/requested_reviewers" \
    -f "reviewers[]=copilot-swe-agent" --silent 2>/dev/null || true

  # Post the fix instruction as a review comment to trigger Copilot
  gh api "repos/$owner/$repo/issues/$pr_num/comments" \
    -f body="@copilot-swe-agent $instruction" --silent 2>/dev/null || {
    # Fallback: try the copilot handle without -swe-agent suffix
    gh api "repos/$owner/$repo/issues/$pr_num/comments" \
      -f body="@copilot $instruction" --silent 2>/dev/null || true
  }

  echo "PR #$pr_num: assigned Copilot coding agent to fix the build failure."
}

# --- State tracking via PR comments ---

get_attempt_count() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4"

  local comments
  comments=$(gh api "repos/$owner/$repo/issues/$pr_num/comments" --jq \
    "[.[].body | select(contains(\"$STATE_MARKER$head_sha:\"))] | length" 2>/dev/null || echo "0")

  echo "$comments"
}

record_attempt() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4" attempt_num="$5"

  local marker="$STATE_MARKER$head_sha:$attempt_num -->"

  gh api "repos/$owner/$repo/issues/$pr_num/comments" \
    -f body="$marker" --silent

  echo "PR #$pr_num: recorded attempt $attempt_num for SHA $head_sha"
}
