#!/usr/bin/env bash
# fixer.sh — invoke Copilot CLI and post comment or commit the fix

COMMIT_MARKER="[auto-pr-fixer]"
STATE_MARKER="<!-- auto-pr-fixer-state:"

fix_pr() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4" logs="$5" mode="$6"

  local prompt
  prompt=$(build_prompt "$owner" "$repo" "$pr_num" "$logs")

  if [[ "$mode" == "comment" ]]; then
    post_comment "$owner" "$repo" "$pr_num" "$head_sha" "$logs" "$prompt"
  else
    commit_fix "$owner" "$repo" "$pr_num" "$head_sha" "$prompt"
  fi
}

build_prompt() {
  local owner="$1" repo="$2" pr_num="$3" logs="$4"

  cat <<EOF
Fix the CI build failure in PR #$pr_num of $owner/$repo.

The following are the relevant error logs from the failing CI build:

\`\`\`
$logs
\`\`\`

Please identify the root cause and provide a fix.
Only modify the minimum set of files needed to fix the build.
Do not modify CI workflow files, lockfiles, or configuration files unless the error is directly in those files.
EOF
}

post_comment() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4" logs="$5" prompt="$6"

  # Invoke Copilot CLI
  local suggestion
  suggestion=$(invoke_copilot "$prompt" 2>/dev/null || echo "_Could not generate a fix suggestion. Please review the logs manually._")

  # Truncate logs for the comment
  local display_logs="$logs"
  if [[ "${#display_logs}" -gt 3000 ]]; then
    display_logs="${display_logs:0:3000}"$'\n... [truncated]'
  fi

  local body
  body=$(cat <<EOF
## 🤖 Auto PR Fixer $COMMIT_MARKER

**CI build failure detected.** Here's what I found:

<details>
<summary>Error Logs (click to expand)</summary>

\`\`\`
$display_logs
\`\`\`
</details>

### Suggested Fix

$suggestion

---
_Generated by [auto-pr-fixer](https://github.com/chrischangcode/auto-pr-fixer) for SHA \`$head_sha\`_
EOF
)

  gh api "repos/$owner/$repo/issues/$pr_num/comments" \
    -f body="$body" --silent

  echo "PR #$pr_num: posted fix suggestion as comment."
}

commit_fix() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4" prompt="$5"

  # Re-check head SHA hasn't changed
  local current_sha
  current_sha=$(gh api "repos/$owner/$repo/pulls/$pr_num" --jq '.head.sha')
  if [[ "$current_sha" != "$head_sha" ]]; then
    echo "PR #$pr_num: head SHA changed ($head_sha -> $current_sha), aborting commit."
    return
  fi

  # Get PR branch
  local pr_branch
  pr_branch=$(gh api "repos/$owner/$repo/pulls/$pr_num" --jq '.head.ref')

  # Attempt fix via Copilot CLI
  local fix_output
  if ! fix_output=$(invoke_copilot "$prompt" 2>&1); then
    echo "PR #$pr_num: Copilot CLI failed, falling back to comment mode."
    post_comment "$owner" "$repo" "$pr_num" "$head_sha" "" "$prompt"
    return
  fi

  echo "Copilot CLI output:"
  echo "$fix_output"

  # Check for protected path modifications
  local changed_files
  changed_files=$(git diff --name-only 2>/dev/null || true)

  if [[ -n "$changed_files" ]]; then
    for file in $changed_files; do
      for pattern in $CFG_PROTECTED_PATHS; do
        # shellcheck disable=SC2254
        case "$file" in
          $pattern)
            echo "Blocked modification to protected path: $file"
            git checkout HEAD -- "$file" 2>/dev/null || true
            ;;
        esac
      done
    done

    git add -A
    git commit -m "fix: auto-fix CI failure $COMMIT_MARKER" || {
      echo "PR #$pr_num: nothing to commit after fix."
      return
    }
    git push origin "$pr_branch" || {
      echo "PR #$pr_num: push failed."
      return
    }

    echo "PR #$pr_num: committed and pushed fix."
  else
    echo "PR #$pr_num: no file changes produced by Copilot CLI."
  fi
}

invoke_copilot() {
  local prompt="$1"

  # Use gh copilot to suggest a fix
  # GH_PROMPT_DISABLE prevents interactive prompts
  GH_PROMPT_DISABLE=1 gh copilot suggest -t shell "$prompt" 2>&1
}

# --- State tracking via PR comments ---

get_attempt_count() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4"

  local comments
  comments=$(gh api "repos/$owner/$repo/issues/$pr_num/comments" --jq \
    "[.[].body | select(contains(\"$STATE_MARKER$head_sha:\"))] | length" 2>/dev/null || echo "0")

  echo "$comments"
}

record_attempt() {
  local owner="$1" repo="$2" pr_num="$3" head_sha="$4" attempt_num="$5"

  local marker="$STATE_MARKER$head_sha:$attempt_num -->"

  gh api "repos/$owner/$repo/issues/$pr_num/comments" \
    -f body="$marker" --silent

  echo "PR #$pr_num: recorded attempt $attempt_num for SHA $head_sha"
}
